config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
  	resources :comments
    member do
      put "like", to: "pins#upvote"
    end
  end
  root "pins#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :pins
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :pin
  belongs_to :user
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  acts_as_votable
  belongs_to :category
  belongs_to :user
  has_many :comments
  has_attached_file :image, styles: {medium: "300x300>"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @pin = Pin.find(params[:pin_id])
    @comment = Comment.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.pin_id = @pin.id

    if @comment.save
      redirect_to pin_path(@pin)
    else
      render 'new'
    end
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]

	def index
    if params[:category].blank?
      @pins = Pin.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @pins = Pin.where(category_id: @category_id).order("created_at DESC")
    end
	end

  def show
    @comments = Comment.where(pin_id: @pin)
  end

	def new
		@pin = current_user.pins.build
	end

	def create
		@pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: "Succesfully created Post"
    else
      render 'new'
    end
	end

  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Post was Succesfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path
  end

  def upvote
    @pin.upvote_by current_user
    redirect_to :back
  end

	private

	def pin_params
		params.require(:pin).permit(:title, :description, :image, :category_id)
	end

  def find_pin
    @pin = Pin.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/comments/_form.html.haml
= simple_form_for([@pin, @pin.comments.build]) do |f|
  = f.input :content, label: "Reply to Thread"
  = f.button :submit, class: "button"

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title VizualizeIt
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .container
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .navbar-brand= link_to "VizualizeIt", root_path
      / Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        - if user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li.newPost= link_to "New Post", new_pin_path, class: "nvli1"
            %li= link_to "All Posts", root_path
            / Button trigger modal
            %li.category{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"}
              Categories
            / Modal
            #myModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
              .modal-dialog{:role => "document"}
                .modal-content
                  .modal-header
                    %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                      %span{"aria-hidden" => "true"} &times;
                    %h4#myModalLabel.modal-title Choose a Category
                  .modal-body
                    - Category.all.each do |category|
                      %li.categories= link_to category.name, pins_path(category: category.name)

            %li= link_to "Account", edit_user_registration_path
            %li.signout= link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Sign Up", new_user_registration_path
            %li= link_to "Sign In", new_user_session_path
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"
    = yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: {multipart: true} do |f|
  - if @pin.errors.any?
    #errors
      %h2
      = pluralize(@pin.errors.count, "error")
      prevented this Pin from saving
      %ul
        - @pin.error.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :title, input_html: {class: 'form-control'}

  .form-group
    = f.input :image, input_html: {class: 'form-control'}

  .form-group
    %label= "Choose a Category"
    = f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a Category"}

  .form-group
    = f.input :description, input_html: {class: 'form-control'}

  / = f.button :submit, class: "btn btn-primary"
  %button.btn.btn-primary{:type => "submit"} Create Post

app/views/pins/edit.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 New Post
      .panel-body
        %strong.center Current Image
        %br
        %h1 Edit Post
        = image_tag @pin.image.url(:medium)
        = simple_form_for @pin, html: {multipart: true} do |f|
          - if @pin.errors.any?
            #errors
              %h2
              = pluralize(@pin.errors.count, "error")
              prevented this Pin from saving
              %ul
                - @pin.error.full_messages.each do |msg|
                  %li= msg

          .form-group
            = f.input :title, input_html: {class: 'form-control'}

          .form-group
            = f.input :image, input_html: {class: 'form-control'}

          .form-group
            %label= "Choose a Category"
            = f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a Category"}

          .form-group
            = f.input :description, input_html: {class: 'form-control'}

          / = f.button :submit, class: "btn btn-primary"

          %button.btn.btn-success{:type => "submit"} Update Post

        = link_to "Cancel", pin_path

app/views/pins/index.html.haml
#pins.transitions-enabled
  - @pins.each do |pin|
    .box.panel.panel-default
      = link_to (image_tag pin.image.url), pin
      .panel-body
        %h2= link_to pin.title, pin
        %p= "Comments:"
        %p= pin.comments.count
        %span.glyphicon.glyphicon-heart
          = pin.get_upvotes.size
        %p.user
          Submitted by:
          = pin.user.username

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 New Post
      .panel-body
        = render 'form'

app/views/pins/show.html.haml
#pin_show.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel-heading.pin_image
        = image_tag @pin.image.url
      .panel-body
        %h1= @pin.title
        %p.description= @pin.description
        %p.user
          Submitted by:
          = @pin.user.username
      .panel-footer
        .row
          .col-md-6
            .btn-group.pull-left
              = link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
                %span.glyphicon.glyphicon-heart
                  = @pin.get_upvotes.size
              - if user_signed_in?
                = link_to "Edit", edit_pin_path, class: "showbtn btn btn-default"
                = link_to "Delete", pin_path, method: :delete, data: {confirm: "Are you sure?"}, class: "deletebtn btn btn-default"


  #comments.col-md-6.col-md-offset-3
    .panel.panel-default
      .panel-body
        %h2.comment_count= pluralize(@pin.comments.count, "Comment")
        - @comments.each do |comment|
          .comment
            %p.username= comment.user.name
            %p.content= comment.content

        = render "comments/form"